services:
  # ---------------------------
  # PostgreSQL Database
  # ---------------------------
  db:
    image: postgres:15
    container_name: sales_db
    restart: always
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d salesdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ---------------------------
  # CSV Loader Service
  # ---------------------------
  loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    container_name: sales_loader
    environment:
      DB_HOST: db
      POSTGRES_DB: salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy

  # ---------------------------
  # Flask API Service
  # ---------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: sales_api
    restart: always
    environment:
      DB_HOST: db
      POSTGRES_DB: salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
      loader:
        condition: service_completed_successfully
    ports:
      - "5000:5000"

  # ---------------------------
  # Streamlit Dashboard
  # ---------------------------
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: sales_dashboard
    restart: always
    depends_on:
      api:
        condition: service_started
    ports:
      - "8501:8501"

# ---------------------------
# Named Volumes
# ---------------------------
volumes:
  pgdata:
